#EXERCICIO

CREATE TABLE FABRICANTES(
	COD_FABRICANTE INT,
    NOM_FABRICANTE VARCHAR (100),
    SITE_FABRICANTE VARCHAR (250),
    IDF_ATIVO VARCHAR (1),
    PRIMARY KEY (COD_FABRICANTE));
    
    
CREATE TABLE CATEGORIA(
		COD_CATEGORIA INT,
        NOM_CATEGORIA VARCHAR (45),
        IDF_ATIVO VARCHAR (1));
        
   SHOW TABLES;     
        